### ISSUE TITLE
class question

### ISSUE THREAD

**Issue by Dhaizei** [koknat/callGraph#19]
i find it couldn't find class,
such as 
class A: 
    def __init__(self):
          pass 
    def forward(self):
          pass
only identity functions,

**Comment by koknat** [comment]
Correct, callGraph does not parse 'class'.  It only parses function names and calls.

**Comment by Dhaizei** [comment]
i have some suggest：
1、add the flowing code to make output better
use utf8;
use open qw(:std :encoding(utf8));
2、i try jsnout，but it have one question. such as：
   "demo_20230202.py:post" : {
      "calls" : {
         "demo_20230202.py:condb_save" : 1,
         "demo_20230202.py:Process2" : 1,
         "demo_20230202.py:Process1" : 1
      } 
      the 1 never be changed，i think that it is number of occurrences，but it don't work

**Comment by koknat** [comment]
Hi Dhaizei,
Thanks for your suggestions
1) At which line number should this code be added?
2) I've changed the jsnOut functionality to use number of occurrences (instead of always '1')

**Comment by Dhaizei** [comment]
Hi koknat，
1、At which line number should this code be added?
Because i found output would be messy if there is Chinese.At the begining of code,this code can be added. it can make output using utf8.
2、I was wondering how callGraph could handle multiple languages in a project.can you give me some suggestion?

**Comment by Dhaizei** [comment]
such  as :  this code could  be added at 3 line number

**Comment by koknat** [comment]
1) Thanks, I've merged in your UTF8 change
2) You could limit each execution of callGraph to one language.
For example:
callGraph *.pl
callGraph *.py

**Comment by Dhaizei** [comment]
thinks

**Comment by Dhaizei** [comment]
hi koknat:
     I want to get class , can callGraph gei this?  can adding regular expression work?

**Comment by koknat** [comment]
I suspect that parsing of class would be challenging, and I don't have time to try this myself.
If you want to try it:
In sub defineSyntax, create a set of regexes for 'class' for all languages, within data structure $languageSyntax.
In sub parsefiles, use $languageSyntax->{class}{$language} when parsing the source file.
Keep in mind that different source files may contain different styles of using spaces (except for Python).  This makes it more difficult to determine when a function or class ends.
Enhance the data structures to account for class, since multiple classes may contain a function with the same name.
If you intend to push your changes into the main branch, please ensure that parsing of class works properly in various languages.

**Comment by Dhaizei** [comment]
thanks.
